language: python
script:
- python -m pytest -v
deploy:
  provider: heroku
  api_key:
   secure: "bHD7ZT+cABmGZoZoPosle8TJHBkx7277CmKdfifj1Ki8XxuZbmRB1nVk+4y2PEZgwsExEV9RIj1TqAnvLFsaGCNwA1X9h8cntiXS7rnwx9hlIgx/5E4s3u4IdC7WVCpf/c6FgklYAUGKK3SEwvaztuhSt6UOcQLXhFBCmDIUrFNGAHg0YhVTqWdNvfXlzr7RxOoQwpATNCzPbhSzeiGL5y15BUxvWw3Zt9mUrispmPrbrPIaAMz+XjgOfr/03zbKhm1BYByxrYkkBvo42IaN17en94JKHVgXOBxQ4ZBLZRbBxjBfpxAH5PUjgGGOjNqrPFAB7lhBvUg2+6WYuhBDBWK3XwyOdaSRprV0x+dqJH45pCOuVJ5muOcLQWVIVERIWieTaCDC2AgnKwcNOtfO69k95SBxJ1s/RI36jBWQl9m1poyHy0YS6sztGe60E0eK8VtuOD2SnIfqkEkHJj3yf+Aoc0CGAb91FpErVqldayN0iC83g4LgrnsYTig691OpYQSzBOZsZNX7h41NnAPyb+KhH12cGL94kSoguYQGr/QENPN1lsHrfVb9tBoYPL4SJ4kH0+B6qZgo4pxD6rJvEi1m+kGVGJ92JscwxjzQHlRSpzwysBiHXuKutaBPkafnf7l2CtPXcxCeyPifUGrZzb7pkTdRqYgBeDb8rC9wlnc="
  on: 
    all_branches: true
