language: python
script:
- python -m pytest -v
deploy:
  provider: heroku
  api_key:
   secure: "lrW3AiKfT9RA9kDKPiz8Iji/ZI0iAIHQck24uTKrw3pLFsHbJi40CZS/4QMQvL69AZ/IjWHU3QZCwBg1wfu55ZDxh5b9xg0wUF9I1IDPYp7iv9KmRG8V7ZSQT+lPGHQxWh0LRAuFfIseLAoQK5vFvIYfRGI4V/IDAEgxkrnrwONfDWGg/+WnaK6ltUIS4CJmdFXZaiqn6YLKNkP0xugazTqA2tufyGjq2u1o6Y+UZRFPILt3Ge8zVOTlwnBUB4WXAphDTmK22trWfDu7Rp3WqE3ajA1OYWZOpXH0FEUwDrAa7pwiY1a7SKiFKq9Wv+FXf3Hr9jmdxDPs23xW0gngxV0k4h/bmsxdNcQgftAhwiCDvjlUx0VI+dU+p+G8LB23inC+afJ0TqZEGsENGiwImeXf4YtMGlL2l8qQkEcBGLFc6W1EvXZL24oJVs2ee68CozBtry98hDQUmVVI8/ZzwabnheaqNUEXlhJ88wte9wg0IYMvQ49XyXZliGcfbUK/TyMlhyRvMrZueXnJnPDYl5PcHxxA31hZYGE4w/WnJHE24MKcS/oHKLd7Co4NlfYa7VOjj8YLdr4Idph/tv9Q6K0pTx7hG/LVOT4YwFxu95migsUQj+E6D7LSuRfSfF7uY7VtTcInrMEYtSam+oBpt+iVd4M1aRz9vyVSAIr58BE="
  on: 
    all_branches: true
