language: python
script:
- python -m pytest -v
deploy:
  provider: heroku
  api_key:
   secure: "cTPI3YZQr0pLFtY75Emqtjgb9DYDnH5dS0c/Z6O9DRQn2WjuT1BX3683ArsSRgeO4Z9Meng6IZLq+hv44sWNBlS4NM4hazaGbeWCHJbUf4ndQPGFXVcqrzfQ+3Kn8kDNVsvzXVNOlcla2tpEmyoqIMNLBdSJgL8KBGD0Zbi8xTrxTe8F+1bzMcmDFeOxCj4rdXpt9aJkePUa/VTK3uGyjcHTLsE7lh8F7a+3ADA21odiQZwhCo9HS6wN7Vb4QAR8sMBB6j1FOL17cKw5doRSNBFtubAeG7HQKOWeLgZ7xk6uQfLv5KOcc2hdZN2CVtmqyN5rC3Rg8kiK/b/J9WpN548OoIOWfDj57mTmrdvkYqLWL8zx88JghTeYRde2Sbz2oSuWObErsLEQYvZny82pBIC+67GdulouUVX32JrN1HziHoCSZ7fnoeSvQ78Fboz2iCtnyuXn6DxdRsIQN0iuQuwc1g0quk+ATezvtR5JNlxuToLLDNtiDGWgFwMoWuzau0jh7S32gRJ28dl5H/ROcIVRopci6FXs03eJW/Ebi5+mHCoWVhCisLeiJNjMnYt/cptGpI8Pe5NLGb75PH8WOm0PGSsI47J96j4bz+UMHrRjeuZ1zLtkM25UVeemoXvyEGHMGi/gTOh9vsVcLontTCQ46zgod/sAo0u0tHen7k0="
  on: 
    all_branches: true
