language: python
script:
  - python -m pytest -v
deploy:
  provider: heroku
api_key:
   secure: ucpiAnhBZQfZtnMfweR2GH/7AHjYri2qRxAqSPIr1tt9sxCtMeyvqlSfasLk6Ttmp6yBDZ3Mu+FfctRDqyCZxCNFzRV62dsksNqBZ9uKu8Nron349LpPymhj2IMKCHOosxJ/W1Sqt9//OspD14KPiGtNYOP7STDFE+cMagrLNu4RW2CLpKrg0i7gT4bt9AefCEjpGzMWwd3wI1ksmorgSq1i0FoxScxCfoifFOk+yI0GvAPr40AmykEOz+/lBiYFwy0/VrnqYBRQmtype+QCzKVslFZfCno9RgS9YwjB57CoIvZeUKUzjh1HtpvC+p0JO101EWAuctJjEkYkBcEp/j6KYWGAmzvOxd4UKmwE24ycu45ibsqK9VVMT0bbL7XlGMfCTkyAGBHGgVIRxqdJe/ECl+Ryq8aLOxW9TejcU6iOFxiQFLgMx58t8KVl0Ftg0L4NnvEsZChypHHYc2+yqELl7+ceeAgRgNdB1UAl4nsedf7OEeaeO4WtXuphyCtIyMM2XROvy7SZk+Na/Gr3fI19S+HKNz0GE9QNFgZLNAPWyaeFyAIWwtwJTDWUjZr4KEC82JaueD5YHOOCG8xkJBr2eLxxg2oabqQyibM8b5L6AaDd2hSRzZ2vyqszYlLFw8EJz+N2j5eRgVDF/8e6VMyA4RqtDGLjN24vd3SIIf4=
true:
  repo: pmagnemi20/cicd
