language: python
script:
- python -m pytest -v
deploy:
  provider: heroku
  api_key:
    secure: ImqiAyffPczvslgUm218+1RCSNyxkOkGXEBfWKMf1a3hNr38fxjhqmEmrxGWO0gwxhk7oiEJTVHc5OHB1DofFg/JIa39l5lEGkMzJFW80jrvi/LCaNhu1aF3e8zQkcO1VrEceXINSDNoKf6l11CYXw711Tupts6HEozWDzXWfY3ITvorfvqUIO5PlVR0vTgLB14IUSYksEoqikQ61SnULOBvpEkOKkdlMZpPPvNj8ogHQsmUOX97rnrdPaK1eYsbmEbySJ6wXG1ZKAoluQpRbZbKF8Qghq6XqKG1y0H2Mu504tQvVofJOIg45O/ckVLd1THjFlFVjdUlA0VkfI6ZxO15bQuOyEKhXUz5dCIJIQn+W/SVvF+PzggwMaN1LW10FHuI4LjmC7oBQAi6n5xEsY8MgrBpTiIR0V2YEBwCZA4zqW2kSFsWW2k+3Dq7TSwDHEKSHhbOHFO/KhK9qQsyyMhOquzig3S88xTzqK97mP2ApVfgIetstDcpn9menct2bs5UHg5bw7eWNaXUSmvTBDY+eoOqu56HMOcNoA/ocnxbmHd+IVN7YhJ4MIw6PncAal2Eyb/vv/9NBezGit7YGtc/wQnu3m7UHl0TVBYMcaVRJrTTEdvOZ0nh9p4vLxNuGq02CpZ/hhHDr7Qe5hoZZppFfGcgNi9A0KRiaqDdfAY=
  on:
    all_branches: true
