language: python
script:
  - python -m pytest -v
deploy:
  provider: heroku
  api_key:
    secure: HkREKv8Eu277vSHuMuqc8e2NKc2ZjNMmg3pO8y7TSPI/1dybUkaopgHAsrvbUFwNQHTDoT/c6dxiOugYIpvTylDKfmmg+68VyzsSABoZnUg7lXdTt027pirzgK+FKT3VrznKGDbRBoMHV5NaNVpmNnIPeqC3JX+mtm5clJBEAcwhlWbebxE9qBkEtRKgb/5NhCSVc2VAtW/pJgzvW+gCz5LBkMGjHZXgVFG741DDgcwrHM6KcB73ZQQZrbqi7Y51f0StHPltkyW5rDWsiN3D5004i8M4qPLT3xUI7sk/orIqbnsqFvjxK6RrYgioMzDIb1zXV4HDDx7ZGdC2djp39yiy9gOK6AvUgsRqlNKgRAxJTMl+KCYdSBiqsRFivwkNRqtZnM53SCbN9/+IUrq0koLCh+MMsz3eY9AciHGBhywx8kJGozUVGvQjpo2csjtlqZPGZ24GR8hUWI4iieBej2dpGUwENZzD+1zXO1mfIDaH6qFXP0Dnx8qXirLfbfSQLxn1obmziJ1YgrJU7h2MIIfpmddFzqrD78+6iyFVbC5bWKiNKtgLBSlo5sJypoz156fEaZkilX3vczhDTkIx5DGoA70SGuIYpIoeQZ9mxSMc2MmA39rV/hj+wi2oRhU06LqxPLHwQylMiCTlAutetCHKAuwMJoiqX8cEC2fVHO0=
true:
  repo: pmagnemi20/cicd
